
# use travis-ci docker based infrastructure
sudo: false

before_script:
  - git submodule init
  - git submodule update --recursive

language: java
install: ant

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
